config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'lists/new', to: 'lists#new'
  # post 'lists', to: 'lists#create'
  # get 'lists', to: 'lists#index'
  # get 'lists/:id', to: 'lists#show', as: :list
  root to: "lists#index"
  resources :lists, only: [:new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

<%= link_to 'Go back to all lists', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
<%= cl_image_tag list.photo.key, height: 300, crop: :fill %>

  <% end %>
</ul>
<%= link_to "create new list", new_list_path%>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>

app/views/lists/show.html.erb
<h1 class="m-2"><%= @list.name  %></h1>
  <hr>
<div class="container">
    <div class="row">
          <% @list.bookmarks.each do |bookmark| %>
      <div class="col-6 d-flex">

        <div><% url = "https://image.tmdb.org/t/p/w1#{bookmark.movie.poster_url}"%>
          <%= image_tag url, alt:"poster", width: "300px" %>
        </div>
        <div class="px-2 ">
            <p><strong><%= bookmark.comment %></strong></p>
            <h4 class="card-title font-weight-bold"><%= bookmark.movie.title %></h4>
            <h6 class="card_text"><%= bookmark.movie.overview %></h6>
            <h6><strong><%= "Rating:"%></strong></h6>
            <h6><%= "#{bookmark.movie.rating}" %></h6>
            <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } do %>
            <strong><i class="far fa-trash-alt" height= 100px></i></strong>
            <% end %>
        </div>
      </div>
        <% end %>
    </div>
</div>

    <button class="m-2"><%= link_to 'Add Movie', new_list_bookmark_path(@list) %></button>
    <button class="m-2"><%= link_to 'Back', root_path %></button>